name = "UnknownFlows"
uuid = "e5c750db-9ad0-4848-a9d0-9ea581a25cf4"
authors = ["Gregory Wagner <wagner.greg@gmail.com>"]
version = "0.1.0"

[deps]
Oceananigans = "9e8cae18-63c1-5223-a75c-80ca9d6e9a09"
